### ISSUE TITLE
How can we (the community) contribute to this distro? It's awesome!

### ISSUE THREAD

**Issue by DontUseGithub** [adioskid/bentoo#2]
Most distros have a list of such recommendations, what would be yours?

**Comment by adioskid** [comment]
Well, it is a 'a little more easy' version of Funtoo to begin users or anyone else.

as a Funtoo based distro, is faster, stable, secure and you have all control about all.

**Comment by adioskid** [comment]
But you can help with feedback, suggestion and criticism.

the system is open and free, you can do anything and create a pull or an issue about you found or did.

our telegram group : https://t.me/joinchat/DG0l5Rez0MRt4p2GHnNohQ
